#!/bin/bash

. ../conf/tools.sh

for package in $PACKAGES; do
  grep -nriR "$1" $ROOT_DIR/src/$package | egrep '\.[py|mako|coffee|scss]' | egrep -v \.svn | egrep -v \~ | egrep -v \.pyc | egrep -v compiled
done;
